spring:
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:h2:mem:myDevCamp
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true